### ISSUE TITLE
Dependency error: "usr/bin/ld: cannot find -lquadprog"

### ISSUE THREAD

**Issue by pulver22** [msorour/gripper_workspace_spheres_grasping_algorithm_basic#1]
As in the title, when launching the first command:
`reset && cmake .. && make -j7 && ./grasping_algorithm ../gripper_pcd_model`

I obtained the error 
`usr/bin/ld: cannot find -lquadprog`

Because some dependecy is missing (probably not specified in the cmake file).

**Comment by msorour** [comment]
Please install quadprog++ (https://github.com/liuq/QuadProgpp)
we have updated the install instructions.
Thanks.
